import "./globals.css";
import Navbar from "./components/Navbar";
import { AuthProvider } from "./contexts/AuthContext";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" data-theme="cupcake">
        <body>
        <AuthProvider>
            <Navbar />
            <div>{/* navbar sabit, içerik biraz aşağıda */}
                {children}
            </div>
        </AuthProvider>
        </body>
        </html>
    );
}