import "./globals.css";
import Navbar from "./components/Navbar";
import { AuthProvider } from "./contexts/AuthContext";
import { ToastProvider } from "./components/ToastContext";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
export default function RootLayout({ children }) {
    return (
        <html lang="en" data-theme="cupcake">
        <body>
        <ToastProvider>
        <AuthProvider>
            <Navbar />
            <div>
                {children}
            </div>
        </AuthProvider>
        </ToastProvider>
        </body>
        </html>
    );
}